# Generated by Django 4.2.7 on 2023-12-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('m', 'Maintenance'), ('a', 'Available'), ('o', 'On loan')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
