# Generated by Django 4.2.7 on 2024-01-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('a', 'Available'), ('m', 'Maintenance'), ('o', 'On loan')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
